version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    image: personal-inventory
    ports:
      - 80:80
    volumes:
      - .:/var/www/app

  mongodb:
    image: mongo:4.0.0
    volumes:
      - ./data/db:/data/db
